version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devops_postgres_staging
    restart: unless-stopped
    environment:
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devopsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U igor -d devopsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: devops_zookeeper_staging
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  flask-app:
    build: .
    container_name: devops_flask_staging
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://igor:password@postgres:5432/devopsdb
    volumes:
      - ./:/app

volumes:
  postgres_data: