apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-chart.fullname" . }}-ingress
  labels:
    app: {{ .Values.appName }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: flask-helm-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "flask-chart.fullname" . }}-svc
            port:
              number: {{ .Values.service.port }}