apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: {{ .Values.namespace }}
  labels:
    app: flask-app
    environment: {{ .Values.flask.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.flask.port }}
        envFrom:
        - configMapRef:
            name: flask-config
        - secretRef:
            name: flask-secret
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.flask.port }}
          initialDelaySeconds: 10
          periodSeconds: 5