apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: "super-secret-key-change-me"
  DB_PASSWORD: "{{ .Values.postgres.password }}"
  MAIL_USERNAME: "{{ .Values.mail.username }}"
  MAIL_PASSWORD: "{{ .Values.mail.password }}"