apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: staging
type: Opaque
stringData:
  SECRET_KEY: "super-secret-key-change-me"
  DB_PASSWORD: "password"
  MAIL_USERNAME: "ikix46@gmail.com"
  MAIL_PASSWORD: "lwvazkncvvktuuye"