namespace: monitoring

prometheus:
  image: prom/prometheus:latest
  port: 9090
  nodePort: 30090
  memory:
    request: "128Mi"
    limit: "256Mi"

grafana:
  image: grafana/grafana:latest
  port: 3000
  nodePort: 30300
  adminPassword: "admin123"
  memory:
    request: "128Mi"
    limit: "256Mi"
