name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 155.212.165.190
        username: igor
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/devops-project-website
          git fetch origin
          git reset --hard origin/main
          git clean -fd
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn