name: Deploy to Staging (K8s)

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            
            cd ~/devops-project-website
            git fetch origin
            git reset --hard origin/staging
            
            # Собрать образ
            docker build -t flask-app-k8s:latest .
            
            # Загрузить в K3s
            docker save flask-app-k8s:latest | sudo k3s ctr images import -
            
            # Деплой Flask
            sudo helm upgrade --install flask-app ./helm/flask-chart --namespace staging --create-namespace --kubeconfig /etc/rancher/k3s/k3s.yaml
            
            # Деплой мониторинга
            sudo helm upgrade --install monitoring ./helm/monitoring-chart --namespace monitoring --create-namespace --kubeconfig /etc/rancher/k3s/k3s.yaml
            
            # Перезапустить поды
            sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n staging rollout restart deployment flask-app
            
            # Проверить
            sleep 15
            curl -f http://localhost:31927/health || curl -f http://155.212.165.190:31927/health || true