name: Deploy to Staging (K8s)

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops-project-website
            git fetch origin
            git reset --hard origin/staging
            
            # Собрать образ
            docker build -t flask-app-k8s:latest .
            
            # Загрузить в K3s
            docker save flask-app-k8s:latest | sudo k3s ctr images import -
            
            # Деплой Flask
            helm upgrade --install flask-app ./helm/flask-chart --namespace staging --create-namespace
            
            # Деплой мониторинга
            helm upgrade --install monitoring ./helm/monitoring-chart --namespace monitoring --create-namespace
            
            # Перезапустить поды с новым образом
            kubectl -n staging rollout restart deployment flask-app
            
            # Проверить
            sleep 10
            curl -f http://localhost:31927/health || exit 1